name: m2interact
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pandas=2.2.3
  - numpy=2.0.2
  - scikit-learn=1.5.2
  - scikit-bio=0.6.2
  - scipy=1.13.1
  - matplotlib=3.9.3
  - seaborn=0.13.2
  - biom-format=2.1.16
