name: m2interact
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pandas=1.5.2
  - numpy=1.24.3
  - scikit-learn=0.24.1
  - scikit-bio=0.5.8
  - matplotlib=3.6.2
  - seaborn=0.13.2
